/*INSERINDO VALORES DE PAIS, ESTADO E CIDADE*/
INSERT INTO PAIS VALUES (NULL,'BRASIL','AMERICA',8.516000,1822,2143,77.0,'DEMOCRACIA','BRASILIA','REAL');
INSERT INTO ESTADO VALUES (NULL,'PERNAMBUCO','PE','NORDESTE','RECIFE',1);
INSERT INTO CIDADE VALUES (NULL,'PETROLINA',354.317,18701121,1);
INSERT INTO ESTADO VALUES (NULL,'BAHIA','BA','NORDESTE','SALVADOR',1);
INSERT INTO CIDADE VALUES (NULL,'JUAZEIRO',218.162,18780715,2);


/* INSERINDO VALORES EM PONTOS TURISTICOS */

INSERT INTO PONTOS_TURISTICOS VALUES (NULL,'BODÓDROMO','RESTAURANTE','SIM','SIM',1);
INSERT INTO PONTOS_TURISTICOS VALUES (NULL,'ILHA_DO_RODEADOR','ILHA','SIM','SIM',1);
INSERT INTO PONTOS_TURISTICOS VALUES (NULL,'CENTRO_DE_ARTES_ANA_DAS_CARRANCAS','MUSEU_DE_ARTES','SIM','NÃO',1);
INSERT INTO PONTOS_TURISTICOS VALUES (NULL,'ILHA_DO_FOGO','ILHA','SIM','SIM',1);
INSERT INTO PONTOS_TURISTICOS VALUES (NULL,'PARQUE_ZÔO_BOTANICO_DA_CAATINGA','ZOOLÓGICO','SIM','NÃO',1);
INSERT INTO PONTOS_TURISTICOS VALUES (NULL,'PETROLINA_ANTIGA','ARÉA_HISTÓRICA','SIM','SIM',1);


SELECT * FROM PAIS;
SELECT * FROM ESTADO;
SELECT * FROM CIDADE;
SELECT * FROM PONTOS_TURISTICOS;

SELECT  ID_CIDADE, NOME_TUR, SERVICOS
FROM CIDADE, PONTOS_TURISTICOS
WHERE ID_CIDADE = 1; 

SELECT  ID_CIDADE, NOME_TUR, SERVICOS
FROM CIDADE
INNER JOIN PONTOS_TURISTICOS
ON ID_CIDADE = 1 ;

SELECT  ID_CIDADE, NOME_TUR, SERVICOS
FROM CIDADE
INNER JOIN PONTOS_TURISTICOS
ON ID_CIDADE = 2 ;

SELECT  ID_CIDADE, NOME_TUR, SERVICOS
FROM CIDADE
INNER JOIN PONTOS_TURISTICOS
WHERE ID_CIDADE = 2 ;


SELECT  ID_CIDADE, NOME_TUR,SERVICOS, PUBLICO 
FROM CIDADE
INNER JOIN PONTOS_TURISTICOS
ON PUBLICO = 'SIM';

ALTER TABLE PONTOS_TURISTICOS
RENAME COLUMN NOME TO NOME_TUR; /* ALTERA O NOME DA TABELA*/
   
SELECT COUNT(*) AS QNT_DE_PONTOS_TURISTICOS
FROM PONTOS_TURISTICOS; /* CONTA A QUANTIDADE DE REGISTRO EM UMA TABELA*/
   
SELECT SUM(POPULACAO)/* SOMA COLUNAS DAS TABELAS*/
FROM CIDADE;
	
SELECT AVG(POPULACAO) /*DÁ O VALOR MÉDIO DE DETERMINADA COLUNA*/
AS MÉDIA_DE_POPULAÇÃO
FROM CIDADE;

 
UPDATE PAIS
SET POPULACAO = 214.300000
WHERE NOME =  'BRASIL';

/* ALTERAÇÃO DE INFORMAÇÕES NO BANCO DE DADOS*/

UPDATE PONTOS_TURISTICOS
SET TIPO =' ATRATIVO'
WHERE ID = 1;

SELECT NOME, NOME_TUR, PUBLICO
FROM CIDADE 
INNER JOIN PONTOS_TURISTICOS
ON NOME = 'PETROLINA'
WHERE PUBLICO = 'SIM';

SELECT NOME, NOME_TUR, PUBLICO
FROM CIDADE 
INNER JOIN PONTOS_TURISTICOS
ON NOME = 'PETROLINA'
WHERE PUBLICO = 'NAO'
ORDER BY NOME ASC;

SELECT NOME, NOME_TUR, PUBLICO
FROM CIDADE 
INNER JOIN PONTOS_TURISTICOS
ON NOME = 'PETROLINA'
WHERE PUBLICO = 'SIM'
ORDER BY NOME ASC;


SELECT NOME_TUR, SERVICOS, IDTURISTICO
FROM PONTOS_TURISTICOS
WHERE NOME_TUR = SOME
(SELECT NOME_TUR
FROM PONTOS_TURISTICOS
WHERE IDTURISTICO = 3);          