CREATE DATABASE GUIATUR;

USE GUIATUR;


CREATE TABLE PAIS (

   IDPAIS INT PRIMARY KEY AUTO_INCREMENT,
   NOME VARCHAR (50) NOT NULL,
   CONTINENTE ENUM ('ÁSIA','AMERICA','OCEANIA','ANTARTIDA','EUROPA') NOT NULL,
   AREA VARCHAR (10) NOT NULL,
   INDEPENDENCIA VARCHAR (4),
   POPULACAO VARCHAR(15),
   EXPECTATIVA_DE_VIDA  DECIMAL (4,1), 
   GOVERNO ENUM ('MONARQUIA','DEMOCRACIA','REPUBLICA') NOT NULL,
   CAPITAL VARCHAR (50) NOT NULL,
   MOEDA VARCHAR (30) NOT NULL
   );


CREATE TABLE ESTADO (

   IDESTADO INT PRIMARY KEY AUTO_INCREMENT,
   NOME VARCHAR (30) NOT NULL,
   SIGLA CHAR (2) NOT NULL,
   REGIAO VARCHAR (20),
   CAPITAL VARCHAR (20) NOT NULL,
   ID_PAIS INT,
   FOREIGN KEY (ID_PAIS)
   REFERENCES PAIS(IDPAIS)
   
   );


CREATE TABLE CIDADE (
  
   IDCIDADE INT PRIMARY KEY AUTO_INCREMENT,
   NOME VARCHAR (30) NOT NULL,
   POPULACAO VARCHAR (15),
   DATA_CRIACAO DATE  NOT NULL,
   ID_ESTADO INT,
   FOREIGN KEY (ID_ESTADO)
   REFERENCES ESTADO(IDESTADO)
  
   );

CREATE TABLE PONTOS_TURISTICOS(

   IDTURISTICO INT PRIMARY KEY AUTO_INCREMENT,
   NOME VARCHAR(100) NOT NULL,
   SERVICOS VARCHAR (100) NOT NULL,
   ATRATIVO ENUM ('SIM','NÃO'),
   PUBLICO ENUM ('SIM','NAO'),
   ID_CIDADE INT,
   FOREIGN KEY (ID_CIDADE)
   REFERENCES CIDADE(IDCIDADE)
);

 CREATE TABLE LINGUAGEM_PAIS(
       IDLINGUAGEM INT PRIMARY KEY AUTO_INCREMENT,
       CÓD_PAIS INT (10),
       LINGUAGEM VARCHAR (30) NOT NULL,
       OFICIAL ENUM ('SIM','NAO') NOT NULL,
       FOREIGN KEY (IDLINGUAGEM)
       REFERENCES PAIS(IDPAIS)
	   );
